export const SET_LANG = "SET_LANG";

export const SET_LAYOUT = "SET_LAYOUT";

export const SET_CHANNEL = "SET_CHANNEL";

export const SET_USER_ID = "SET_USER_ID";

export const SET_ID_SEQ = "SET_ID_SEQ";

export const SET_CUSTOMER_SERVICE_ID = "SET_CUSTOMER_SERVICE_ID";

export const SET_TRANSLATE = "SET_TRANSLATE";

export const SET_TOKEN = "SET_TOKEN";

export const SET_HISTORY = "SET_HISTORY";

export const SET_ENDLISTS = "SET_ENDLISTS";

export const UPDATE_PROGRESS = "UPDATE_PROGRESS"; // 进度

export const SET_WAITLISTS = "SET_WAITLISTS";

export const SET_SESSIONLISTS = "SET_SESSIONLISTS";

export const ADD_SESSIONLISTS = "ADD_SESSIONLISTS";

export const UPDATE_SESSION_PREVIEW = "UPDATE_SESSION_PREVIEW"; //列表预览更新

export const UPDATE_SESSION_OFFLINE = "UPDATE_SESSION_OFFLINE";

export const REMOVE_SESSIONLISTS = "REMOVE_SESSIONLISTS";

export const UPDATE_CURRENT_SESSION = "UPDATE_CURRENT_SESSION";

export const SET_USERINFO = "SET_USERINFO";

export const SET_SHOWWAIT = "SET_SHOWWAIT";

export const SET_WINDOWSIZE = "SET_WINDOWSIZE";
export const SET_ADMIT_LIMIT = "SET_ADMIT_LIMIT";

export const SET_RESPONSE = "SET_RESPONSE";
export const SET_GENERALRES = "SET_GENERALRES";
export const SET_FAMILIAR = "SET_FAMILIAR";
export const SET_HOT = "SET_HOT";

export const REMVOE_SESSIONLISTS = "REMVOE_SESSIONLISTS";

export const ADD_BROWSING = "ADD_BROWSING";

export const REMVOE_BROWSING = "REMVOE_BROWSING";

export const SET_DELETETO = "SET_DELETETO";

export const SET_LUYOU = "SET_LUYOU";

export const SET_COMPILETO = "SET_COMPILETO";

export const SET_GREETINGS = "SET_GREETINGS";

export const SET_REMINDERSETTING = "SET_REMINDERSETTING"; // 设置通知列表

export const SET_DEPARTMENTUSERS = "SET_DEPARTMENTUSERS"; // 同事列表

export const SET_SESSION_COLLEAGUE_LIST = "SET_SESSION_COLLEAGUE_LIST"; //设置同事会话列表

export const UPDATE_SESSION_COLLEAGUE_PREVIEW = "UPDATE_SESSION_COLLEAGUE_PREVIEW"; //同事列表预览更新

export const UPDATE_SESSION_COLLEAGUE_ONLINE = "UPDATE_SESSION_COLLEAGUE_ONLINE"; //同事在线状态

export const SET_UNFOLD = "SET_UNFOLD";

export const SET_ONLINE = "SET_ONLINE";

export const SET_SESSION_TIME = "SET_SESSION_TIME";

export const ADD_ENDLISTS = "ADD_ENDLISTS";

export const ADD_SESSIONLISTSBOTTOM = "ADD_SESSIONLISTSBOTTOM";

export const SET_WAITNUM = "SET_WAITNUM";

export const SET_UNREAD_NUMBER = "SET_UNREAD_NUMBER";

// 上传
export const ADD_UPLOAD_LIST = "ADD_UPLOAD_LIST";

export const DELETE_UPLOAD_LIST = "DELETE_UPLOAD_LIST";

export const SET_TOAST_TEXT = "SET_TOAST_TEXT";

export const SET_FILESIZE = "SET_FILESIZE";

export const SET_BUBBLES = "SET_BUBBLES";
