/*----- 最近会话模块 -----*/
export const UPDATE_CURRENT_SESSION = 'UPDATE_CURRENT_SESSION'
export const UPDATE_SESSION = 'UPDATE_SESSION'//更新单个
export const UPDATE_SESSION_BATCH = 'UPDATE_SESSION_BATCH'//批量更新
export const DELETE_SESSION = 'DELETE_SESSION'//删除单个
export const SET_SELECTIONCODEKEY = 'SET_SELECTIONCODEKEY'

/*----- 好友模块 -----*/
export const SET_GROUP_LIST = 'SET_GROUP_LIST'
export const DEL_GROUP_LIST = 'DEL_GROUP_LIST'
export const SET_FRIEND_LIST = 'SET_FRIEND_LIST'
export const ADD_FRIEND_INFO = 'ADD_FRIEND_INFO'
export const DEL_FRIEND_INFO = 'DEL_FRIEND_INFO'
export const SET_GROUP_MEMBER = 'SET_GROUP_MEMBER'
export const UPDATA_MEMBER_INFO = 'UPDATA_MEMBER_INFO'
export const SET_BLACK_LIST = 'SET_BLACK_LIST'

/*----- 消息模块 -----*/
export const SET_RECORD = 'SET_RECORD'
export const ADD_MESSAGE = 'ADD_MESSAGE'
export const UPDATE_MESSAGE = 'UPDATE_MESSAGE'
export const UPDATE_MESSAGE_READ = 'UPDATE_MESSAGE_READ'
export const DELETE_MESSAGE = 'DELETE_MESSAGE'
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE'
export const SET_UNREAD_NUMBER = 'SET_UNREAD_NUMBER'
export const SET_AT = 'SET_AT'
export const SET_AFFICHE = 'SET_AFFICHE'
export const DELETE_AFFICHE = 'DELETE_AFFICHE'
export const SET_DRAFT = 'SET_DRAFT'
export const SET_DELETE_INFO = 'SET_DELETE_INFO'
export const SET_FORWARD_INFO = 'SET_FORWARD_INFO'
export const SET_LAST_GROUP_MSG = 'SET_LAST_GROUP_MSG'
export const SET_INVITE = 'SET_INVITE'
export const SET_VERIFY_HISTORY = 'SET_VERIFY_HISTORY'
export const SET_IS_TYPING = 'SET_IS_TYPING'


/*----- 音视频模块 -----*/
export const MUTE_VIDEO = 'MUTE_VIDEO'
export const ADD_VIDEO_VIEW = 'ADD_VIDEO_VIEW'
export const DELETE_VIDEO_VIEW = 'DELETE_VIDEO_VIEW'
export const UPDATE_VIDEO_INFO = 'UPDATE_VIDEO_INFO'
export const UPDATE_AUDIO_STATE = 'UPDATE_AUDIO_STATE'//更新音视频状态

/*----- 其他 -----*/
export const SET_LANG = 'SET_LANG'
export const SET_USER_INFO = 'SET_USER_INFO'
export const SET_USER_TOKEN = 'SET_USER_TOKEN'
export const SET_TOAST_TEXT = 'SET_TOAST_TEXT'
export const SET_TOAST_BOX = 'SET_TOAST_BOX'
export const SET_CROWDTOAST_TEXT = 'SET_CROWDTOAST_TEXT'
export const SET_MOUSE_RIGHT_MSG = 'SET_MOUSE_RIGHT_MSG'
export const SET_NOTICE_SETTING = 'SET_NOTICE_SETTING'
export const ADD_UPLOAD_LIST = 'ADD_UPLOAD_LIST'
export const DELETE_UPLOAD_LIST = 'DELETE_UPLOAD_LIST'
export const UPDATE_PROGRESS = 'UPDATE_PROGRESS'
export const SET_ROUTE_NAME = 'SET_ROUTE_NAME'
export const SET_HAS_CURRENT_MSG = 'SET_HAS_CURRENT_MSG'
export const SET_AT_OBJ = 'SET_AT_OBJ'
export const SET_GROUP_INVITE = 'SET_GROUP_INVITE'
export const SET_RIGHT = 'SET_RIGHT'

export const SET_LOGIN_FAIL = 'SET_LOGIN_FAIL'
export const SET_LAYOUT = 'SET_LAYOUT'
export const SET_MYEMOJI = 'SET_MYEMOJI'
export const SET_VIDEOCLOSE = 'SET_VIDEOCLOSE'
export const SET_BUBBLES = 'SET_BUBBLES'
export const SET_BACKURL = 'SET_BACKURL'
export const SET_WINDOWSIZE = 'SET_WINDOWSIZE'
export const SET_FRIENDCARD = 'SET_FRIENDCARD'
export const SET_ISALLOWMOBILE = 'SET_ISALLOWMOBILE'
export const SET_FILESIZE = 'SET_FILESIZE'
export const SET_DELETEGROUPMEMBER = 'SET_DELETEGROUPMEMBER'
export const SET_FORWARD_LIST = 'SET_FORWARD_LIST'
export const SET_RECORDS = 'SET_RECORDS'
export const SET_TOFIRST = 'SET_TOFIRST'
export const PUSHTOKEN= 'PUSHTOKEN'
export const CLEARTOKEN= 'CLEARTOKEN'
 
